import json
import sys
from pathlib import Path

from src.core.token_usage_tracker import (
    TokenUsageTracker,
    build_token_usage_run_reports,
    estimate_text_tokens,
    estimate_usage_from_texts,
    extract_chat_completions_usage,
    extract_links,
    extract_responses_usage,
    extract_user_query_from_chat_messages,
    extract_user_query_from_responses_input,
    missing_usage,
    next_token_usage_run_id,
    normalize_sites_from_urls,
    sanitize_run_text,
)


def _record(query_text: str = "Analyze https://example.com/article", **overrides):
    record = {
        "event": "llm_token_usage",
        "run_id": "run_test",
        "timestamp": "2026-05-06T10:30:00.000-04:00",
        "provider": "openai-oauth-bridge",
        "status": "missing_usage",
        "query_text": query_text,
        "sites_scanned_or_analyzed": ["example.com"],
        "total_input_tokens": None,
        "total_output_tokens": None,
        "usage_source": "missing",
        "is_estimate": False,
    }
    record.update(overrides)
    return record


def test_tracker_creates_log_dir_and_appends_jsonl(tmp_path):
    log_dir = tmp_path / "token-usage"
    tracker = TokenUsageTracker(log_dir=log_dir)

    tracker.record(_record())
    tracker.record(_record("Second query"))

    assert log_dir.exists()
    lines = (log_dir / "token-usage.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(lines) == 2
    assert json.loads(lines[0])["event"] == "llm_token_usage"
    assert json.loads(lines[1])["query_text"] == "Second query"


def test_tracker_record_many_appends_jsonl_batch(tmp_path):
    log_dir = tmp_path / "token-usage"
    tracker = TokenUsageTracker(log_dir=log_dir)

    tracker.record_many([_record(), _record("Second query")])

    lines = (log_dir / "token-usage.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(lines) == 2
    assert json.loads(lines[0])["query_text"] == "Analyze https://example.com/article"
    assert json.loads(lines[1])["query_text"] == "Second query"


def test_next_token_usage_run_id_uses_four_digit_sequence_and_text(tmp_path):
    log_dir = tmp_path / "token-usage"
    log_dir.mkdir()
    (log_dir / "0001 - Existing run.json").write_text("{}", encoding="utf-8")
    (log_dir / "token-usage.jsonl").write_text(
        json.dumps({"run_id": "0002 - Existing raw run"}) + "\n",
        encoding="utf-8",
    )

    run_id = next_token_usage_run_id("Trump: China/deal? Xi", log_dir)

    assert run_id == "0003 - Trump Chinadeal Xi"


def test_sanitize_run_text_collapses_whitespace_and_caps_length():
    assert sanitize_run_text("  Trump   China\n deal  Xi  ") == "Trump China deal Xi"
    assert sanitize_run_text("<bad>: story?") == "bad story"
    assert len(sanitize_run_text("x" * 100)) == 80


def test_run_report_uses_description_fallback_and_ui_agent_name():
    reports = build_token_usage_run_reports(
        [
            _record(
                agent_name="semantic_query_expander",
                query_text=(
                    "Canonical headline: Trump Economic Approval Rating\n"
                    "Description: Trump Counterterrorism Adviser Brands Tucker Carlson an Enemy\n"
                    "Seed article title: Trump Economic Approval Rating"
                ),
                run_id="run_missing_metadata",
                timestamp="2026-05-16T04:15:13.000-04:00",
            )
        ]
    )

    assert list(reports) == [
        "0001 - Trump Counterterrorism Adviser Brands Tucker Carlson an Enemy.json"
    ]
    report = next(iter(reports.values()))
    assert report["run_id"] == (
        "0001 - Trump Counterterrorism Adviser Brands Tucker Carlson an Enemy"
    )
    assert report["agents"][0]["agent_name"] == "STORY_PARSER"


def test_run_report_uses_untitled_when_metadata_is_missing():
    reports = build_token_usage_run_reports(
        [
            _record(
                query_text=(
                    "Analyze the political bias of this news source based on reporting style"
                ),
                run_id="run_missing_metadata",
                timestamp="2026-05-16T04:15:13.000-04:00",
            )
        ]
    )

    assert list(reports) == ["0001 - untitled.json"]


def test_tracker_writes_separate_pretty_run_report_files(tmp_path):
    log_dir = tmp_path / "token-usage"
    tracker = TokenUsageTracker(log_dir=log_dir)

    tracker.record_many(
        [
            _record(
                agent_name="profile_reader",
                cached_input_tokens=20,
                date="2026-05-16",
                duration_ms=2000,
                model="gpt-5.4",
                query_text="Prompt generated by the system",
                reasoning_tokens=2,
                run_id="0001 - Trump China deal Xi",
                run_text="Trump China deal Xi",
                status="success",
                time="04:15:13",
                timestamp="2026-05-16T04:15:13.000-04:00",
                total_input_tokens=100,
                total_output_tokens=10,
            ),
            _record(
                agent_name="bias_classifier",
                cached_input_tokens=30,
                date="2026-05-16",
                duration_ms=3000,
                model="gpt-5.5",
                query_text="Second generated prompt",
                reasoning_tokens=3,
                run_id="0001 - Trump China deal Xi",
                run_text="Trump China deal Xi",
                status="success",
                time="04:15:20",
                timestamp="2026-05-16T04:15:20.000-04:00",
                total_input_tokens=200,
                total_output_tokens=25,
            ),
        ]
    )

    report_path = log_dir / "0001 - Trump China deal Xi.json"
    report_text = report_path.read_text(encoding="utf-8")
    report = json.loads(report_text)

    assert "\n  \"agents\": [\n" in report_text
    assert report == {
        "run_id": "0001 - Trump China deal Xi",
        "date_started": "2026-05-16",
        "time_started": "04:15:13",
        "agent_calls": 2,
        "agents": [
            {
                "agent_name": "PROFILE_READER",
                "model": "gpt-5.4",
                "input_tokens": 100,
                "cached_tokens": 20,
                "output_tokens": 10,
                "reasoning_tokens": 2,
                "time_started": "04:15:13",
                "time_ended": "04:15:15",
            },
            {
                "agent_name": "BIAS_CLASSIFIER",
                "model": "gpt-5.5",
                "input_tokens": 200,
                "cached_tokens": 30,
                "output_tokens": 25,
                "reasoning_tokens": 3,
                "time_started": "04:15:20",
                "time_ended": "04:15:23",
            },
        ],
        "time_ended": "04:15:23",
        "total_duration": "0:00:10",
        "models": [
            {
                "model": "gpt-5.4",
                "total_input_tokens": 100,
                "total_cached_tokens": 20,
                "total_output_tokens": 10,
                "total_reasoning_tokens": 2,
            },
            {
                "model": "gpt-5.5",
                "total_input_tokens": 200,
                "total_cached_tokens": 30,
                "total_output_tokens": 25,
                "total_reasoning_tokens": 3,
            },
        ],
    }


def test_build_token_usage_run_reports_numbers_raw_run_ids_by_time():
    reports = build_token_usage_run_reports(
        [
            _record(
                run_id="run_second",
                run_text="Second run",
                timestamp="2026-05-16T04:16:00.000-04:00",
            ),
            _record(
                run_id="run_first",
                run_text="First run",
                timestamp="2026-05-16T04:15:00.000-04:00",
            ),
        ]
    )

    assert list(reports) == ["0001 - First run.json", "0002 - Second run.json"]


def test_chat_completions_usage_maps_provider_fields():
    usage = extract_chat_completions_usage(
        {
            "usage": {
                "prompt_tokens": 111,
                "completion_tokens": 222,
                "total_tokens": 333,
                "prompt_tokens_details": {"cached_tokens": 44},
                "completion_tokens_details": {"reasoning_tokens": 55},
            }
        }
    )

    assert usage == {
        "total_input_tokens": 111,
        "total_output_tokens": 222,
        "total_tokens": 333,
        "cached_input_tokens": 44,
        "reasoning_tokens": 55,
        "usage_source": "provider_usage",
        "is_estimate": False,
    }


def test_responses_usage_maps_provider_fields():
    usage = extract_responses_usage(
        {
            "usage": {
                "input_tokens": 111,
                "output_tokens": 222,
                "total_tokens": 333,
                "input_tokens_details": {"cached_tokens": 44},
                "output_tokens_details": {"reasoning_tokens": 55},
            }
        }
    )

    assert usage == {
        "total_input_tokens": 111,
        "total_output_tokens": 222,
        "total_tokens": 333,
        "cached_input_tokens": 44,
        "reasoning_tokens": 55,
        "usage_source": "provider_usage",
        "is_estimate": False,
    }


def test_missing_usage_has_null_totals_and_not_estimated():
    assert missing_usage() == {
        "total_input_tokens": None,
        "total_output_tokens": None,
        "total_tokens": None,
        "cached_input_tokens": None,
        "reasoning_tokens": None,
        "usage_source": "missing",
        "is_estimate": False,
    }
    assert extract_chat_completions_usage({})["usage_source"] == "missing"
    assert extract_responses_usage({})["is_estimate"] is False


def test_provider_usage_requires_numeric_input_and_output_counts():
    usage = extract_chat_completions_usage({"usage": {"total_tokens": 333}})

    assert usage == missing_usage()


def test_estimate_text_tokens_counts_normal_text():
    count = estimate_text_tokens("Analyze this source for political framing.")

    assert isinstance(count, int)
    assert count > 0


def test_estimate_text_tokens_returns_zero_for_empty_text():
    assert estimate_text_tokens(None) == 0
    assert estimate_text_tokens("") == 0


def test_estimate_usage_from_texts_returns_local_estimate_shape():
    usage = estimate_usage_from_texts(
        input_text="Analyze https://example.com/article",
        output_text="Brief answer.",
        model="gpt-5.3-codex",
    )

    assert isinstance(usage["total_input_tokens"], int)
    assert usage["total_input_tokens"] > 0
    assert isinstance(usage["total_output_tokens"], int)
    assert usage["total_output_tokens"] > 0
    assert usage["total_tokens"] == (
        usage["total_input_tokens"] + usage["total_output_tokens"]
    )
    assert usage["usage_source"] == "local_estimate"
    assert usage["is_estimate"] is True


def test_estimate_text_tokens_falls_back_to_character_estimate(monkeypatch):
    monkeypatch.setitem(sys.modules, "tiktoken", None)

    assert estimate_text_tokens("123456789") == 3


def test_extract_links_from_query_text():
    links = extract_links(
        "Analyze https://example.com/article and https://another-site.com/path)."
    )

    assert links == [
        "https://example.com/article",
        "https://another-site.com/path",
    ]


def test_normalize_sites_from_urls():
    assert normalize_sites_from_urls(
        [
            "https://www.example.com/article",
            "https://another-site.com/path",
            "not a url",
        ]
    ) == ["another-site.com", "example.com", "not a url"]


def test_query_extraction_excludes_system_and_instructions():
    chat_query = extract_user_query_from_chat_messages(
        [
            {"role": "system", "content": "Never log me."},
            {"role": "user", "content": "Analyze https://example.com/article"},
        ]
    )
    responses_query = extract_user_query_from_responses_input(
        [
            {"role": "system", "content": "Never log me."},
            {
                "role": "user",
                "content": [{"type": "input_text", "text": "User visible text"}],
            },
        ]
    )

    assert chat_query == "Analyze https://example.com/article"
    assert responses_query == "User visible text"


def test_gitignore_excludes_token_usage_folder():
    gitignore = Path(".gitignore").read_text(encoding="utf-8")

    assert "/token-usage/" in gitignore
