"""SQLAlchemy database models and utilities."""

from src.database.crud import (
    AgentFindingCRUD,
    AgentHandoffCRUD,
    AnalysisCRUD,
    AnalysisRunCRUD,
    PerformanceCRUD,
    RetrievalCandidateCRUD,
    SourceCRUD,
    SourceFindingCRUD,
    StoryCRUD,
    VisualEvidenceRecordCRUD,
)
from src.database.models import (
    AgentConfiguration,
    AgentFinding,
    AgentHandoff,
    Analysis,
    AnalysisRun,
    Base,
    ChannelProfile,
    RetrievalCandidate,
    SemanticChunk,
    SemanticDocument,
    Source,
    SourceFindingRecord,
    Story,
    VideoPerformance,
    VisualEvidenceRecordModel,
)
from src.database.session import (
    SessionLocal,
    engine,
    get_alembic_revision_status,
    get_db,
    get_session,
    init_db,
    mark_interrupted_analysis_runs,
    run_alembic_upgrade,
)

__all__ = [
    # Models
    "Base",
    "Story",
    "Source",
    "Analysis",
    "AnalysisRun",
    "RetrievalCandidate",
    "SourceFindingRecord",
    "VisualEvidenceRecordModel",
    "VideoPerformance",
    "ChannelProfile",
    "AgentConfiguration",
    "AgentFinding",
    "AgentHandoff",
    "SemanticDocument",
    "SemanticChunk",
    # CRUD
    "StoryCRUD",
    "SourceCRUD",
    "AnalysisCRUD",
    "AgentFindingCRUD",
    "AgentHandoffCRUD",
    "AnalysisRunCRUD",
    "RetrievalCandidateCRUD",
    "SourceFindingCRUD",
    "VisualEvidenceRecordCRUD",
    "PerformanceCRUD",
    # Session
    "engine",
    "SessionLocal",
    "get_db",
    "get_session",
    "get_alembic_revision_status",
    "init_db",
    "mark_interrupted_analysis_runs",
    "run_alembic_upgrade",
]
