#!/usr/bin/env python3
"""Generate human-readable markdown docs from source_registry.yaml.

Run: python scripts/generate_source_docs.py

Outputs regenerated docs to stdout (or a specified output path).
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.services.source_registry import SourceRegistry


def generate_markdown(registry: SourceRegistry) -> str:
    """Generate a comprehensive markdown source list from the registry."""
    lines: list[str] = []
    lines.append("# News Source Registry")
    lines.append("")
    lines.append(
        "> **Auto-generated** from `config/source_registry.yaml`. "
        "Do not edit this file directly."
    )
    lines.append("")

    # Group by bias
    bias_groups: dict[int, list] = {}
    for entry in registry.entries:
        bias_groups.setdefault(entry.bias, []).append(entry)

    for bias in sorted(bias_groups.keys()):
        entries = bias_groups[bias]
        label = registry.get_bias_label(bias)
        lines.append(f"## {label} ({bias:+d})")
        lines.append("")

        for entry in sorted(entries, key=lambda e: e.name):
            lines.append(f"### {entry.name}")
            lines.append(f"- **Domain:** `{entry.domain}`")
            lines.append(f"- **Category:** {entry.category}")
            lines.append(f"- **Factual Rating:** {entry.factual_rating}")
            if entry.rss_urls:
                lines.append("- **RSS Feeds:**")
                for rss in entry.rss_urls:
                    lines.append(f"  - {rss}")
            if entry.search_aliases:
                lines.append(f"- **Aliases:** {', '.join(entry.search_aliases)}")
            if entry.syndication_group:
                lines.append(f"- **Syndication:** {entry.syndication_group}")
            if entry.notes:
                lines.append(f"- **Notes:** {entry.notes}")
            lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Bias | Label | Count |")
    lines.append("|------|-------|-------|")
    for bias in sorted(bias_groups.keys()):
        label = registry.get_bias_label(bias)
        count = len(bias_groups[bias])
        lines.append(f"| {bias:+d} | {label} | {count} |")
    lines.append(f"| | **Total** | **{len(registry.entries)}** |")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    """Generate and optionally write source docs."""
    registry = SourceRegistry()
    md = generate_markdown(registry)

    if len(sys.argv) > 1:
        out_path = Path(sys.argv[1])
        out_path.write_text(md, encoding="utf-8")
        print(f"Written to {out_path}")
    else:
        print(md)


if __name__ == "__main__":
    main()
